<a href="https://colab.research.google.com/github/salsafadilah/tugas-web-html/blob/main/ILOC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = {
    'nama':['salsa','safira','carlita'],
    'usia':[23,24,25],
    'kota':['bogor','depok','jakarta']
}
df = pd.DataFrame(data)

In [ ]:
df.iloc[0]

nama    salsa
usia       23
kota    bogor
Name: 0, dtype: object

In [ ]:
df.iloc[0:2, 1]

0    23
1    24
Name: usia, dtype: int64

In [ ]:
df.iloc[0:4, 2]

0      bogor
1      depok
2    jakarta
Name: kota, dtype: object

In [ ]:
df.iloc[0:3, 0:2]

      nama  usia
0    salsa    23
1   safira    24
2  carlita    25

In [ ]:
df.iloc[ ,0:3]

SyntaxError: invalid syntax (2675299841.py, line 1)

In [ ]:
x = dataset.iloc[:,1:3],values

NameError: name 'dataset' is not defined